
# main menu
[[main]]
name = "Hjem"
url = "/"
weight = 1

[[main]]
name = "Om oss"
weight = 2

[[main]]
parent = "Om oss"
name = "Styret"
url = "/styret"
weight = 1

[[main]]
parent = "Om oss"
name = "LURveleven"
url = "/om-oss"
weight = 2

[[main]]
parent = "Om oss"
name = "Vedtekter"
url = "/vedtekter"
weight = 3

# footer menu
#[[footer]]
#name = "Om oss"
#url = "/om-oss"
#weight = 1

[[footer]]
name = "Personvernerkl√¶ring"
url = "/privacy-policy"
weight = 3
